- hosts: localhost
  tasks:
  - name: Install a list of packages
    apt:
      pkg: 
        - apache2
        - git
        - tree
      state: latest
  
  - name: Start service apache, if not started
    service:
      name: apache2
      state: started
      enabled: yes