- hosts: localhost
  tasks:
  - name: Install a list of packages
    apt:
      pkg: 
        - apache2
        - git
        - tree
      state: latest
      update_cache: yes
  
  - name: Start service apache, if not started
    service:
      name: apache2
      state: started
      enabled: yes
  
  - name: Creating groups with loop
    group:
      name: "{{ item }}"
      state: present
    loop:
      - kaizen
      - devops
      - qa             # ansible-playbook groups.yml 
    become: yes
      

  - name: Create user and add to group
    user: 
      name: saniya
      groups: kaizen,qa
      append: yes
    become: yes        # ansible-playbook -b users.yml #mind -b for sudo   
  
  - name: Create user and add to group
    user: 
      name: tester
      groups: qa
      state: present
   
  - name: Copy file to remote host
    copy:
      src: /root/ansible-hw-b5/Homework1/main.yml
      dest: "~/"

# --syntax-check  