- name: MariaDB 
  hosts: all 
  gather_facts: true 
  become: true 
  vars:
    mysql_root_password: passwd
  tasks: 
    - name: Install mariadb 
      yum: 
        name:
          - mariadb 
          - mariadb-server 
        state: latest 

    - name: Start and enable mariadb 
      service: 
        name: mariadb 
        state: started 
        enabled: yes

    # - name: Create MariaDB database
    #   mysql_db: 
    #     name: "{{ wp_mysql_db }}" 
    #     state: present
    
    # - name: Create MariaDB username and password
    #   mysql_user: 
    #     login_user: root 
    #     login_password: root
    #     name: "{{ wp_mysql_user }}" 
    #     password: "{{ wp_mysql_password }}"
    #     priv: "*.*:ALL, GRANT"

#  - name: Copy ~/.my.cnf to nodes
#     copy: src=.my.cnf dest=/root/.my.cnf
  
