- hosts: all
  tasks:
  - name: Install dependencies for WordPress
    yum:
      name:
        - php
        - php-mysql
      state: present
    become: yes
    when: 

  - name: Upgrade all packages
    yum: 
      name: '*'
      state: latest
    

 