- hosts: all
  sudo: yes
  tasks:
  - name: Install EPEL repo.
    yum:
      name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm 
      state: present
      update_cache: yes
    when: 

  # - name: enable remi-php74
  #   shell: yum-config-manager --enable remi-php74

  - name: Enable remi-php74
    yum_repository:
      name: remi-php74
      description: Remi's PHP 7.4 RPM repository for Linux 7 - $basearch
      baseurl: https://rpms.remirepo.net/enterprise/7/php74/$basearch/
      enabled: yes
      gpgcheck: 1
      gpgkey: http://rpms.remirepo.net/RPM-GPG-KEY-remi
    when:


  
